import {
  arbitrum,
  avalanche,
  base,
  bsc,
  celo,
  fantom,
  gnosis,
  linea,
  mainnet,
  mantle,
  metis,
  moonbeam,
  moonriver,
  optimism,
  polygon,
  polygonZkEvm,
  ronin,
  scroll,
  soneium,
  sonic,
  xLayer,
  zksync,
  plasma,
} from 'viem/chains';

export const RDD_URL = 'https://reference-data-directory.vercel.app';

export const chainIdToRddSlug: Record<number, string> = {
  [mainnet.id]: 'feeds-mainnet',
  [bsc.id]: 'feeds-bsc-mainnet',
  [polygon.id]: 'feeds-matic-mainnet',
  [gnosis.id]: 'feeds-xdai-mainnet',
  [avalanche.id]: 'feeds-avalanche-mainnet',
  [fantom.id]: 'feeds-fantom-mainnet',
  [arbitrum.id]: 'feeds-ethereum-mainnet-arbitrum-1',
  [optimism.id]: 'feeds-ethereum-mainnet-optimism-1',
  [moonriver.id]: 'feeds-kusama-mainnet-moonriver',
  [moonbeam.id]: 'feeds-polkadot-mainnet-moonbeam',
  [metis.id]: 'feeds-ethereum-mainnet-andromeda-1',
  [base.id]: 'feeds-ethereum-mainnet-base-1',
  [celo.id]: 'feeds-celo-mainnet',
  [scroll.id]: 'feeds-ethereum-mainnet-scroll-1',
  [linea.id]: 'feeds-ethereum-mainnet-linea-1',
  [zksync.id]: 'feeds-ethereum-mainnet-zksync-1',
  [polygonZkEvm.id]: 'feeds-ethereum-mainnet-polygon-zkevm-1',
  [soneium.id]: 'feeds-soneium-mainnet',
  [sonic.id]: 'feeds-sonic-mainnet',
  [mantle.id]: 'feeds-ethereum-mainnet-mantle-1',
  [xLayer.id]: 'feeds-ethereum-mainnet-xlayer-1',
  [ronin.id]: 'feeds-ronin-mainnet',
  [plasma.id]: 'feeds-plasma-mainnet',
};
